/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as InnovationRouteImport } from './routes/innovation'
import { Route as DistributorRouteImport } from './routes/distributor'
import { Route as CropsRouteImport } from './routes/crops'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KnowledgeSlugRouteImport } from './routes/knowledge.$slug'
import { Route as CropsSlugNutrientsRouteImport } from './routes/crops_.$slug.nutrients'

const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovationRoute = InnovationRouteImport.update({
  id: '/innovation',
  path: '/innovation',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributorRoute = DistributorRouteImport.update({
  id: '/distributor',
  path: '/distributor',
  getParentRoute: () => rootRouteImport,
} as any)
const CropsRoute = CropsRouteImport.update({
  id: '/crops',
  path: '/crops',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeSlugRoute = KnowledgeSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KnowledgeRoute,
} as any)
const CropsSlugNutrientsRoute = CropsSlugNutrientsRouteImport.update({
  id: '/crops_/$slug/nutrients',
  path: '/crops/$slug/nutrients',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/crops': typeof CropsRoute
  '/distributor': typeof DistributorRoute
  '/innovation': typeof InnovationRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/products': typeof ProductsRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/crops/$slug/nutrients': typeof CropsSlugNutrientsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/crops': typeof CropsRoute
  '/distributor': typeof DistributorRoute
  '/innovation': typeof InnovationRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/products': typeof ProductsRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/crops/$slug/nutrients': typeof CropsSlugNutrientsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/crops': typeof CropsRoute
  '/distributor': typeof DistributorRoute
  '/innovation': typeof InnovationRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/products': typeof ProductsRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/crops_/$slug/nutrients': typeof CropsSlugNutrientsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/crops'
    | '/distributor'
    | '/innovation'
    | '/knowledge'
    | '/products'
    | '/knowledge/$slug'
    | '/crops/$slug/nutrients'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/crops'
    | '/distributor'
    | '/innovation'
    | '/knowledge'
    | '/products'
    | '/knowledge/$slug'
    | '/crops/$slug/nutrients'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/crops'
    | '/distributor'
    | '/innovation'
    | '/knowledge'
    | '/products'
    | '/knowledge/$slug'
    | '/crops_/$slug/nutrients'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  CropsRoute: typeof CropsRoute
  DistributorRoute: typeof DistributorRoute
  InnovationRoute: typeof InnovationRoute
  KnowledgeRoute: typeof KnowledgeRouteWithChildren
  ProductsRoute: typeof ProductsRoute
  CropsSlugNutrientsRoute: typeof CropsSlugNutrientsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovation': {
      id: '/innovation'
      path: '/innovation'
      fullPath: '/innovation'
      preLoaderRoute: typeof InnovationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distributor': {
      id: '/distributor'
      path: '/distributor'
      fullPath: '/distributor'
      preLoaderRoute: typeof DistributorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crops': {
      id: '/crops'
      path: '/crops'
      fullPath: '/crops'
      preLoaderRoute: typeof CropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/$slug': {
      id: '/knowledge/$slug'
      path: '/$slug'
      fullPath: '/knowledge/$slug'
      preLoaderRoute: typeof KnowledgeSlugRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/crops_/$slug/nutrients': {
      id: '/crops_/$slug/nutrients'
      path: '/crops/$slug/nutrients'
      fullPath: '/crops/$slug/nutrients'
      preLoaderRoute: typeof CropsSlugNutrientsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface KnowledgeRouteChildren {
  KnowledgeSlugRoute: typeof KnowledgeSlugRoute
}

const KnowledgeRouteChildren: KnowledgeRouteChildren = {
  KnowledgeSlugRoute: KnowledgeSlugRoute,
}

const KnowledgeRouteWithChildren = KnowledgeRoute._addFileChildren(
  KnowledgeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  CropsRoute: CropsRoute,
  DistributorRoute: DistributorRoute,
  InnovationRoute: InnovationRoute,
  KnowledgeRoute: KnowledgeRouteWithChildren,
  ProductsRoute: ProductsRoute,
  CropsSlugNutrientsRoute: CropsSlugNutrientsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
